---

zabbix_installation_method:             repo
# zabbix_installation_method:             download
zabbix_repo_to_add:                     True

zabbix_version_major:       "3.2"
zabbix_version_minor:       "1"

zabbix_version:             "{{ zabbix_version_major }}-{{ zabbix_version_minor }}"

zabbix_repo_package_url_by_os:
  Ubuntu:       "http://repo.zabbix.com/zabbix/{{ zabbix_version_major }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}+{{ ansible_distribution_release }}_all.deb"
  Debian:       "http://repo.zabbix.com/zabbix/{{ zabbix_version_major }}/debian/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}+{{ ansible_distribution_release }}_all.deb"
  RedHat:       "http://repo.zabbix.com/zabbix/{{ zabbix_version_major }}/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-{{ zabbix_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
  CentOS:       "http://repo.zabbix.com/zabbix/{{ zabbix_version_major }}/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-{{ zabbix_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm"

zabbix_repo_package_url:  "{{ zabbix_repo_package_url_by_os[ ansible_distribution ] | default('none') }}"

ansible_required_package_by_os:
  Ubuntu:       []
  Debian:       []
  RedHat:
    - libselinux-python
  CentOS:
    - libselinux-python

ansible_required_package:  "{{ ansible_required_package_by_os[ ansible_distribution ] | default('none') }}"