---
# Configure Zabbix agent that runs on server

- name: customize Zabbix configuration file
  become: yes
  lineinfile: dest="{{ zabbix_conf_file }}"
              regexp="^{{ item.key }}="
              line="{{ item.key }}={{ item.value }}"
  with_dict: "{{ zabbix_server_config_params }}"
  notify:
    - restart zabbix agent
