---
# Install Zabbix agent from repo apt repository

# -------------------------------------------------------------
#  remove stale version

# if package installation fails, try to remove the package manually
# and then purge the files with 'dpkg -P zabbix-sender'
#
# ref: http://www.silvatechsolutions.com/tech-tips/ubuntu-fixing-the-not-replacing-deleted-config-file

- name: remove stale Zabbix agent
  become: yes
  apt: name={{ item }} state=absent
  with_items: "{{ zabbix_packages }}"
  when: "{{ zabbix_remove_stale_version | bool }}"

- name: purge stale Zabix agent packages
  become: yes
  command: dpkg -P {{ item }}
  with_items: "{{ zabbix_packages }}"
  when: "{{ zabbix_remove_stale_version | bool }}"

- name: remove stale files from previous installation (if any)
  become: yes
  file: name="{{ item }}" state=absent
  with_items: "{{ zabbix_stale_files }}"
  when: "{{ zabbix_remove_stale_version | bool }}"

# -------------------------------------------------------------
#  install new package

- name: install Zabbix agent packages
  become: yes
  apt:  name="{{ item }}={{ zabbix_package_version }}*" state=present
  with_items: "{{ zabbix_packages }}"
  when: "{{ zabbix_package_version != 'latest' }}"

- name: install Zabbix agent packages (latest version)
  become: yes
  apt:  name={{ item }} state=latest
  with_items: "{{ zabbix_packages }}"
  when: "{{ zabbix_package_version == 'latest' }}"