---
# Pre-requisites to execute Ansible zabbix* modules

# -------------------------------------------------------------
#  install packages from repo

- name: install required packages for Ansible zabbix modules
  become: yes
  apt: name={{ item }} state=latest update_cache=yes
  with_items: "{{ ansible_required_packages }}"
  when: ansible_pkg_mgr == "apt"

# -------------------------------------------------------------
#  install packages with python-pip

- include: install_packages_pip.yml