---
# Install Zabbix server from repo apt repository

# -------------------------------------------------------------
#  remove stale version

- name: remove stale Zabbix server
  become: yes
  apt: name={{ item }} state=absent
  with_items: "{{ zabbix_packages }}"
  when: "{{ zabbix_remove_stale_version | bool }}"

- name: purge stale Zabix server packages
  become: yes
  command: dpkg -P {{ item }}
  with_items: "{{ zabbix_packages }}"
  when: "{{ zabbix_remove_stale_version | bool }}"

#  Installation of 'zabbix-frontend-php' will fail if stale files
#  remain from previous installation

- name: remove stale files from previous installation (if any)
  become: yes
  file: name="{{ item }}" state=absent
  with_items: "{{ zabbix_stale_files }}"
  when: "{{ zabbix_remove_stale_version | bool }}"

# -------------------------------------------------------------
#  install new package

- name: install Zabbix server packages
  become: yes
  apt:  name="{{ item }}={{ zabbix_package_version }}*" state=present
  with_items: "{{ zabbix_packages }}"
  when: "{{ zabbix_package_version != 'latest' }}"

- name: install Zabbix server packages (latest version)
  become: yes
  apt:  name={{ item }} state=latest
  with_items: "{{ zabbix_packages }}"
  when: "{{ zabbix_package_version == 'latest' }}"