---

zabbix_installation_method:         repo
# zabbix_installation_method:         download

pip_installation_method:            repo
# pip_installation_method:            download

zabbix_remove_stale_version:        False
zabbix_stale_files:
  - "{{ zabbix_conf_file }}"

zabbix_can_run_docker:              False

zabbix_register_with_server:        True

# zabbix_api_connection_method:       ssh
zabbix_api_connection_method:       local

zabbix_agent_port:                  10050

# connect to Zabbix agent by IP (1) or by hostname (0)
zabbix_host_interface_useip:        1

zabbix_host_interfaces:
  - type: 1
    main: 1
    useip: "{{ zabbix_host_interface_useip }}"
    dns: "{{ ansible_fqdn }}"
    port: "{{ zabbix_agent_port }}"
    ip: "{{ ansible_default_ipv4[ 'address' ] }}"
    # ip: ""

# Zabbix host groups

zabbix_servers_host_group:          "Zabbix servers"

zabbix_default_host_group:          "Ansible registered hosts"
zabbix_additional_host_groups:
#    - "Discovered hosts"
    - "Linux servers"

zabbix_app_specific_host_groups:    []

# Zabbix templates

zabbix_host_os_template:            "Template OS Linux"
zabbix_host_extra_templates:
    - "Template ICMP Ping"

zabbix_host_app_specific_templates:    []

zabbix_server_os_template:          "Template OS Linux"
zabbix_server_extra_templates:
    - "Template App Zabbix Server"