---

zabbix_installation_method:     repo
# zabbix_installation_method:     download

zabbix_timezone_hardcoded:      "US/Pacific-New"
zabbix_timezone:                "{{ zabbix_timezone_hardcoded | default( ansible_date_time[ 'tz' ] ) }}"

zabbix_remove_stale_version:    False
zabbix_stale_files:
  - "{{ zabbix_server_conf_file }}"
  - "{{ zabbix_frontend_conf_file }}"